"""
    Generated by idoml processor

"""

from airflow.providers.docker.operators.docker import DockerOperator
from airflow import DAG
from airflow.utils.dates import days_ago
from airflow.models import Variable

import docker

AWS_ACCESS_KEY_ID = Variable.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = Variable.get("AWS_SECRET_ACCESS_KEY")
MINIO_ENDPOINT = Variable.get("MINIO_ENDPOINT")
MLFLOW_TRACKING_URI = Variable.get("MLFLOW_TRACKING_URI")
MLFLOW_S3_ENDPOINT_URL = Variable.get("MLFLOW_S3_ENDPOINT_URL")

default_args = {
    "project_id": "lcld-v0.0.0",
    "queue": "default",
}

dag = DAG(
    "lcld-v0.0.0",
    default_args=default_args,
    start_date=days_ago(1),
    description="""
Created with Elyra 3.16.0.dev0 pipeline editor using `lcld.pipeline`.
    """,
    schedule_interval="@once",
    is_paused_upon_creation=False,
    catchup=False,
)


# Operator source: idoml-pipeline-example-lcld/data_cleaning.ipynb

op_node_data_cleaning = DockerOperator(
    task_id="data_cleaning",
    image="sntyulin/idoml-base",
    docker_url="unix://var/run/docker.sock",
    command=[
        "sh",
        "-c",
        "mkdir -p ./jupyter-work-dir/ && cd ./jupyter-work-dir/ && echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/main/elyra/airflow/bootstrapper.py' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/main/elyra/airflow/bootstrapper.py --output bootstrapper.py && echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/main/etc/generic/requirements-elyra.txt' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/main/etc/generic/requirements-elyra.txt --output requirements-elyra.txt && python3 -m pip install packaging && python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py --pipeline-name 'lcld' --cos-endpoint http://minio.idoml.uni.lux --cos-bucket idoml --cos-directory 'lcld-v0.0.0' --cos-dependencies-archive 'data_cleaning-node-data-cleaning.tar.gz' --file 'idoml-pipeline-example-lcld/data_cleaning.ipynb' ",
    ],
    environment={
        "AWS_ACCESS_KEY_ID": AWS_ACCESS_KEY_ID,
        "AWS_SECRET_ACCESS_KEY": AWS_SECRET_ACCESS_KEY,
        "MINIO_ENDPOINT": MINIO_ENDPOINT,
        "MLFLOW_TRACKING_URI": MLFLOW_TRACKING_URI,
        "MLFLOW_S3_ENDPOINT_URL": MLFLOW_S3_ENDPOINT_URL,
        "ELYRA_RUNTIME_ENV": "idoml",
        "ELYRA_ENABLE_PIPELINE_INFO": "True",
        "ELYRA_RUN_NAME": "lcld-{{ ts_nodash }}",
    },
    mount_tmp_dir=False,
    network_mode="bridge",
    dag=dag,
)


# Operator source: idoml-pipeline-example-lcld/feature_engineering.ipynb

op_node_feature_engineering = DockerOperator(
    task_id="feature_engineering",
    image="sntyulin/idoml-base",
    docker_url="unix://var/run/docker.sock",
    command=[
        "sh",
        "-c",
        "mkdir -p ./jupyter-work-dir/ && cd ./jupyter-work-dir/ && echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/main/elyra/airflow/bootstrapper.py' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/main/elyra/airflow/bootstrapper.py --output bootstrapper.py && echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/main/etc/generic/requirements-elyra.txt' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/main/etc/generic/requirements-elyra.txt --output requirements-elyra.txt && python3 -m pip install packaging && python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py --pipeline-name 'lcld' --cos-endpoint http://minio.idoml.uni.lux --cos-bucket idoml --cos-directory 'lcld-v0.0.0' --cos-dependencies-archive 'feature_engineering-node-feature-engineering.tar.gz' --file 'idoml-pipeline-example-lcld/feature_engineering.ipynb' ",
    ],
    environment={
        "AWS_ACCESS_KEY_ID": AWS_ACCESS_KEY_ID,
        "AWS_SECRET_ACCESS_KEY": AWS_SECRET_ACCESS_KEY,
        "MINIO_ENDPOINT": MINIO_ENDPOINT,
        "MLFLOW_TRACKING_URI": MLFLOW_TRACKING_URI,
        "MLFLOW_S3_ENDPOINT_URL": MLFLOW_S3_ENDPOINT_URL,
        "ELYRA_RUNTIME_ENV": "idoml",
        "ELYRA_ENABLE_PIPELINE_INFO": "True",
        "ELYRA_RUN_NAME": "lcld-{{ ts_nodash }}",
    },
    mount_tmp_dir=False,
    network_mode="bridge",
    dag=dag,
)

op_node_feature_engineering << op_node_data_cleaning


# Operator source: idoml-pipeline-example-lcld/model_training.ipynb

op_7fcb6898_92e4_479a_ad6b_ea2699d93245 = DockerOperator(
    task_id="model_training",
    image="sntyulin/idoml-base",
    docker_url="unix://var/run/docker.sock",
    command=[
        "sh",
        "-c",
        "mkdir -p ./jupyter-work-dir/ && cd ./jupyter-work-dir/ && echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/main/elyra/airflow/bootstrapper.py' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/main/elyra/airflow/bootstrapper.py --output bootstrapper.py && echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/main/etc/generic/requirements-elyra.txt' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/main/etc/generic/requirements-elyra.txt --output requirements-elyra.txt && python3 -m pip install packaging && python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py --pipeline-name 'lcld' --cos-endpoint http://minio.idoml.uni.lux --cos-bucket idoml --cos-directory 'lcld-v0.0.0' --cos-dependencies-archive 'model_training-7fcb6898-92e4-479a-ad6b-ea2699d93245.tar.gz' --file 'idoml-pipeline-example-lcld/model_training.ipynb' ",
    ],
    environment={
        "AWS_ACCESS_KEY_ID": AWS_ACCESS_KEY_ID,
        "AWS_SECRET_ACCESS_KEY": AWS_SECRET_ACCESS_KEY,
        "MINIO_ENDPOINT": MINIO_ENDPOINT,
        "MLFLOW_TRACKING_URI": MLFLOW_TRACKING_URI,
        "MLFLOW_S3_ENDPOINT_URL": MLFLOW_S3_ENDPOINT_URL,
        "ELYRA_RUNTIME_ENV": "idoml",
        "ELYRA_ENABLE_PIPELINE_INFO": "True",
        "ELYRA_RUN_NAME": "lcld-{{ ts_nodash }}",
    },
    mount_tmp_dir=False,
    network_mode="bridge",
    dag=dag,
)

op_7fcb6898_92e4_479a_ad6b_ea2699d93245 << op_node_feature_engineering
