"""
    Generated by idoml processor

"""
from airflow.providers.docker.operators.docker import DockerOperator
from airflow import DAG
from airflow.utils.dates import days_ago
from airflow.models import Variable

import docker

AWS_ACCESS_KEY_ID = Variable.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = Variable.get("AWS_SECRET_ACCESS_KEY")
MINIO_ENDPOINT = Variable.get("MINIO_ENDPOINT")
MLFLOW_TRACKING_URI = Variable.get("MLFLOW_TRACKING_URI")
MLFLOW_S3_ENDPOINT_URL = Variable.get("MLFLOW_S3_ENDPOINT_URL")

default_args = {
    "project_id": "untitled-v0.0.0",
    "queue": "default",
}

dag = DAG(
    "untitled-v0.0.0",
    default_args=default_args,
    start_date=days_ago(1),
    description="""
Created with Elyra 3.16.0.dev0 pipeline editor using `untitled.pipeline`.
    """,
    schedule_interval="@once",
    is_paused_upon_creation=False,
    catchup=False,
)


# Operator source: test/Untitled1.ipynb

op_390f2351_a0d5_4615_abb3_1081a7ff920d = DockerOperator(
    task_id="Untitled1",
    image="ghcr.io/yulinhuang/idoml-python:3.10",
    docker_url="unix://var/run/docker.sock",
    auto_remove="success",
    command=[
        "sh",
        "-c",
        "mkdir -p ./jupyter-work-dir/ && cd ./jupyter-work-dir/ && echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/main/elyra/airflow/bootstrapper.py' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/main/elyra/airflow/bootstrapper.py --output bootstrapper.py && echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/main/etc/generic/requirements-elyra.txt' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/main/etc/generic/requirements-elyra.txt --output requirements-elyra.txt && python3 -m pip install packaging && python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py --pipeline-name 'untitled' --cos-endpoint http://minio.idoml.precision.uni.lux --cos-bucket test-to-delet --cos-directory 'untitled-v0.0.0' --cos-dependencies-archive 'Untitled1-390f2351-a0d5-4615-abb3-1081a7ff920d.tar.gz' --file 'test/Untitled1.ipynb' ",
    ],
    environment={
        "AWS_ACCESS_KEY_ID": AWS_ACCESS_KEY_ID,
        "AWS_SECRET_ACCESS_KEY": AWS_SECRET_ACCESS_KEY,
        "MINIO_ENDPOINT": MINIO_ENDPOINT,
        "MLFLOW_TRACKING_URI": MLFLOW_TRACKING_URI,
        "MLFLOW_S3_ENDPOINT_URL": MLFLOW_S3_ENDPOINT_URL,
        "MLFLOW_EXP_NAME": "untitled-v0.0.0",
        "ELYRA_RUNTIME_ENV": "idoml",
        "ELYRA_ENABLE_PIPELINE_INFO": "True",
        "ELYRA_RUN_NAME": "untitled-{{ ts_nodash }}",
    },
    mount_tmp_dir=False,
    network_mode="bridge",
    dag=dag,
)


# Operator source: test/Untitled2.ipynb

op_355e6a13_3aef_4b0d_8f5e_9779832a80b5 = DockerOperator(
    task_id="Untitled2",
    image="ghcr.io/yulinhuang/idoml-python:3.10",
    docker_url="unix://var/run/docker.sock",
    auto_remove="success",
    command=[
        "sh",
        "-c",
        "mkdir -p ./jupyter-work-dir/ && cd ./jupyter-work-dir/ && echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/main/elyra/airflow/bootstrapper.py' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/main/elyra/airflow/bootstrapper.py --output bootstrapper.py && echo 'Downloading https://raw.githubusercontent.com/elyra-ai/elyra/main/etc/generic/requirements-elyra.txt' && curl --fail -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/elyra-ai/elyra/main/etc/generic/requirements-elyra.txt --output requirements-elyra.txt && python3 -m pip install packaging && python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py --pipeline-name 'untitled' --cos-endpoint http://minio.idoml.precision.uni.lux --cos-bucket test-to-delet --cos-directory 'untitled-v0.0.0' --cos-dependencies-archive 'Untitled2-355e6a13-3aef-4b0d-8f5e-9779832a80b5.tar.gz' --file 'test/Untitled2.ipynb' --outputs 'test.csv;test2.csv' ",
    ],
    environment={
        "AWS_ACCESS_KEY_ID": AWS_ACCESS_KEY_ID,
        "AWS_SECRET_ACCESS_KEY": AWS_SECRET_ACCESS_KEY,
        "MINIO_ENDPOINT": MINIO_ENDPOINT,
        "MLFLOW_TRACKING_URI": MLFLOW_TRACKING_URI,
        "MLFLOW_S3_ENDPOINT_URL": MLFLOW_S3_ENDPOINT_URL,
        "MLFLOW_EXP_NAME": "untitled-v0.0.0",
        "ELYRA_RUNTIME_ENV": "idoml",
        "ELYRA_ENABLE_PIPELINE_INFO": "True",
        "ELYRA_RUN_NAME": "untitled-{{ ts_nodash }}",
    },
    mount_tmp_dir=False,
    network_mode="bridge",
    dag=dag,
)

op_355e6a13_3aef_4b0d_8f5e_9779832a80b5 << op_390f2351_a0d5_4615_abb3_1081a7ff920d
